POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdlb3JnZSIsImlkIjoiNjQ2MmJlNTI5ODAxMGI2NzYwMWY0NGRiIiwiaWF0IjoxNjg0Mjc0MzkxLCJleHAiOjE2ODQyNzc5OTF9.q6YPde2vuOaCfAv3fWuETds5atMxR2lScdKe9BTHX58

{
    "title": "bbb",
    "author": "vvv creanga",
    "url": "wwwioncreanga",
    "likes": "22"
}

###

POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "george",
    "name": "george",
    "password": "georgica"
}

###

POST http://localhost:3001/api/login
content-type: application/json

{
    "username": "george",
    "password": "georgica"
}

###

DELETE http://localhost:3001/api/blogs/6462c1ba19b13708ceb2c4a6
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imdlb3JnZSIsImlkIjoiNjQ2MmJlNTI5ODAxMGI2NzYwMWY0NGRiIiwiaWF0IjoxNjg0MjY4NzAwLCJleHAiOjE2ODQyNzIzMDB9.0_uUAz9S5PZoADW8f9BNDMx-B1dXZh3HuFJzMgi6XQs
